### ISSUE TITLE
Why report memory used as histogram

### ISSUE THREAD

**Issue by LukeDefeo** [kamon-io/kamon-system-metrics#20]
https://github.com/kamon-io/kamon-system-metrics/blob/ac3707932b6f13bcf21e6240ec243d57f5ab6bf8/src/main/scala/kamon/system/jvm/MemoryUsageMetrics.scala#L97

Sorry if this is a dumb question but Im struggling to understand why memory is reported as a histogram. Histograms make sense for latencies where there are a range of values but there can only be one amount of memory used at one time so a gauge makes a lot more sense to my mind

Am i missing something

**Comment by serragnoli** [comment]
Hi @LukeDefeo 
I've seen this in the [documentation](https://github.com/kamon-io/kamon-system-metrics) under **Host System Metrics**:

>  In the sections below, you will see histograms tracking metrics that typically should be recorded with a gauge, but that we couldn't allow because of the need to have a tight control on timings and thread-safety.

I hope it helps.

**Comment by ivantopo** [comment]
Hello there!

So, long time passed but an answer is still good :smile:... The short version is that memory usage should have never been recorded as a histogram and we got that fixed in the 2.x versions.

The longer version is that we want to track behaviors instead of just values. For example, we record the CPU usage every second in a histogram so at the end of the minute you can have one single histogram with 60 measurements of how CPU usage was, which allows you to go from a mere "used X percent of CPU" (just a value) to a heatmap of CPU usage (a representation of behavior):

![image](https://user-images.githubusercontent.com/1302854/68988237-452b2b00-0834-11ea-9655-884da3fe50ce.png)

This is something that makes sense for fast moving indicators like CPU usage but did not make sense at all for memory usage since even though it can change a bit, it rarely jumps up and down so easily. 

Hope this helps, feel free to ask if you need any more info!
