### ISSUE TITLE
Precision loss in the "load average" metric

### ISSUE THREAD

**Issue by camilleoudot** [kamon-io/kamon-system-metrics#23]
The load average metric collected by sigar is returned as an array of doubles (the linux platform for instance provides 2 decimal digits of precision in **/proc/loadavg**), but these values are casted to long values:
https://github.com/kamon-io/kamon-system-metrics/blob/ac3707932b6f13bcf21e6240ec243d57f5ab6bf8/src/main/scala/kamon/system/host/LoadAverageMetrics.scala#L41

Since the load average value are generally small, the truncated values collected by **kamon-system-metrics** are not precise enough to represent the actual load on the platform.

Would it be possible to report the load average multiplied by 100 before conversion instead, or as a new metric?

**Comment by ivantopo** [comment]
Hey @camilleoudot, thanks for mentioning this! We already noticed that this is not ideal and also that this metric really shouldn't be sampled (as we do with CPU usage and other metrics) because if doesn't change that easily (at least the 5m and 15m values) so in the upcoming version it has been moved to be a gauge instead of a sampled histogram and, in Kamon 2.0, gauges allow for floating point values so it will be exactly what gets read from the system!

Some time ago we were also thinking about multiplying the load average and so on, but then the metric would only make sense if everybody new that they need to divide it be 100 before displaying/alerting which wasn't the most ideal case, so we ended up making gauges have `Double` values and move this metric there. How does that sound to you? do you maybe have some use case where it actually makes sense to be sampling this metric?

**Comment by camilleoudot** [comment]
Hi Ivan, thanks for your reply. It's nice to see that the issue has already been seen and addressed in the upcoming version. When is it planned to be released?

As for the "times 100" workaround, I do agree that the current metric should not be changed as it would not be backward-compatible, but it could rather be exposed as a new metric

I think we are going to either wait for the next release with the gauge, or patch the library if we can't wait until then.

Regards

**Comment by ivantopo** [comment]
Hey there! I'm closing this since the new version was already released with this change.
